version: '3.1'

services:
  timer-db:
    image: postgres:13.2
    ports:
      - "12013:5432"
    container_name: timer-db
    environment:
      - POSTGRES_DB=timer
      - POSTGRES_USER=timer
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgresql:
  postgresql_data:
